### ISSUE TITLE
Error in upcoming talk labeled as previous

### ISSUE THREAD

**Issue by oscar-carlsson** [GAPinDNNs/gapindnns.github.io#19]
The talk by Maurice scheduled at 10:30 2024-10-28 is (as of writing this at 09:45 2024-10-28) labeled as a "Previous" seminar talk. See attached picture. 
![image](https://github.com/user-attachments/assets/211f92cd-75ed-4617-a2e5-32345e931025)

My guess is that the check to see if a talk has happened only checks the date and not the time of the talk.

**Comment by PhilippMisofCH** [comment]
Thanks, you are right! I didn't handle daylight saving time... I'm working on it!

**Comment by oscar-carlsson** [comment]
No worries! DST is a common issue as far as I've understood it

**Comment by PhilippMisofCH** [comment]
Should be fixed by 11262e23c43c579ebd34f3fc2ad9fc74fffbf267

**Comment by PhilippMisofCH** [comment]
Note that you might need to clear your cache for the changes to take effect...
